run:
  timeout: 5m
  tests: false  # Skip test files entirely

linters:
  enable:
    - govet
    - ineffassign
    - staticcheck
  disable:
    # Disable errcheck - too noisy for cleanup/defer patterns
    - errcheck
    # Disable unused - many fields reserved for future implementation
    - unused
    # Disable gosimple - stylistic suggestions only
    - gosimple

linters-settings:
  staticcheck:
    checks:
      - all
      - "-SA9003"  # Disable empty branch check
      - "-SA1012"  # Disable nil context check (common in tests)
      - "-SA6002"  # Disable pointer-like argument check
      - "-SA6005"  # Disable EqualFold suggestion

issues:
  exclude-rules:
    # Exclude stub implementations
    - path: stub\.go
      linters:
        - staticcheck
    - path: mysql_stub\.go
      linters:
        - staticcheck
